export const RESET_ERROR_MESSAGE = 'RESET_ERROR_MESSAGE'

export const HRM_SAU_REQUEST = 'HRM_SAU_REQUEST'
export const HRM_SAU_SUCCESS = 'HRM_SAU_SUCCESS'
export const HRM_SAU_FAILURE = 'HRM_SAU_FAILURE'

export const PROCESS_DEFINITION_REQUEST = 'PROCESS_DEFINITION_REQUEST'
export const PROCESS_DEFINITION_SUCCESS = 'PROCESS_DEFINITION_SUCCESS'
export const PROCESS_DEFINITION_FAILURE = 'PROCESS_DEFINITION_FAILURE'

export const PROCESS_DEFINITION_XML_REQUEST = 'PROCESS_DEFINITION_XML_REQUEST'
export const PROCESS_DEFINITION_XML_SUCCESS = 'PROCESS_DEFINITION_XML_SUCCESS'
export const PROCESS_DEFINITION_XML_FAILURE = 'PROCESS_DEFINITION_XML_FAILURE'

export const GET_PERSONAL_REQUEST = 'GET_PERSONAL_REQUEST'
export const GET_PERSONAL_SUCCESS = 'GET_PERSONAL_SUCCESS'
export const GET_PERSONAL_FAILURE = 'GET_PERSONAL_FAILURE'

export const UPDATE_PERSONAL_REQUEST = 'UPDATE_PERSONAL_REQUEST'
export const UPDATE_PERSONAL_SUCCESS = 'UPDATE_PERSONAL_SUCCESS'
export const UPDATE_PERSONAL_FAILURE = 'UPDATE_PERSONAL_FAILURE'

export const NEW_PROCESS_INSTANCE_REQUEST = 'NEW_PROCESS_INSTANCE_REQUEST'
export const NEW_PROCESS_INSTANCE_SUCCESS = 'NEW_PROCESS_INSTANCE_SUCCESS'
export const NEW_PROCESS_INSTANCE_FAILURE = 'NEW_PROCESS_INSTANCE_FAILURE'

export const NEW_PROCESS_INSTANCE_VARIABLES_REQUEST = 'NEW_PROCESS_INSTANCE_VARIABLES_REQUEST'
export const NEW_PROCESS_INSTANCE_VARIABLES_SUCCESS = 'NEW_PROCESS_INSTANCE_VARIABLES_SUCCESS'
export const NEW_PROCESS_INSTANCE_VARIABLES_FAILURE = 'NEW_PROCESS_INSTANCE_VARIABLES_FAILURE'

export const FORM_KEY_REQUEST = 'FORM_KEY_REQUEST'
export const FORM_KEY_SUCCESS = 'FORM_KEY_SUCCESS'
export const FORM_KEY_FAILURE = 'FORM_KEY_FAILURE'

export const TASKS_REQUEST = 'TASKS_REQUEST'
export const TASKS_SUCCESS = 'TASKS_SUCCESS'
export const TASKS_FAILURE = 'TASKS_FAILURE'

export const TASK_FORM_KEY_REQUEST = 'TASK_FORM_KEY_REQUEST'
export const TASK_FORM_KEY_SUCCESS = 'TASK_FORM_KEY_SUCCESS'
export const TASK_FORM_KEY_FAILURE = 'TASK_FORM_KEY_FAILURE'

export const TASK_SUBMITTED_REQUEST = 'TASK_SUBMITTED_REQUEST'
export const TASK_SUBMITTED_SUCCESS = 'TASK_SUBMITTED_SUCCESS'
export const TASK_SUBMITTED_FAILURE = 'TASK_SUBMITTED_FAILURE'

export const TASK_VARIABLES_REQUEST = 'TASK_VARIABLES_REQUEST'
export const TASK_VARIABLES_SUCCESS = 'TASK_VARIABLES_SUCCESS'
export const TASK_VARIABLES_FAILURE = 'TASK_VARIABLES_FAILURE'

export const PROCESS_DEPLOYMENT_REQUEST = 'PROCESS_DEPLOYMENT_REQUEST'
export const PROCESS_DEPLOYMENT_SUCCESS = 'PROCESS_DEPLOYMENT_SUCCESS'
export const PROCESS_DEPLOYMENT_FAILURE = 'PROCESS_DEPLOYMENT_FAILURE'
//              BACKEND API'S
export const INITIATE_GET_DATA_REQUEST = 'INITIATE_GET_DATA_REQUEST';
export const INITIATE_GET_DATA_SUCCESS = 'INITIATE_GET_DATA_SUCCESS';
export const INITIATE_GET_DATA_FAILURE = 'INITIATE_GET_DATA_FAILURE';

export const GET_DEPT_REQUEST = 'GET_DEPT_REQUEST';
export const GET_DEPT_SUCCESS = 'GET_DEPT_SUCCESS';
export const GET_DEPT_FAILURE = 'GET_DEPT_FAILURE';

export const INITIATE_FORM_CREATE_REQUEST = 'INITIATE_FORM_CREATE_REQUEST';
export const INITIATE_FORM_CREATE_SUCCESS = 'INITIATE_FORM_CREATE_SUCCESS';
export const INITIATE_FORM_CREATE_FAILURE = 'INITIATE_FORM_CREATE_FAILURE';

export const CLASSIFICATION_REQUEST = 'CLASSIFICATION_REQUEST'
export const CLASSIFICATION_SUCCESS = 'CLASSIFICATION_SUCCESS'
export const CLASSIFICATION_FAILURE = 'CLASSIFICATION_FAILURE'

export const TYPE_REQUEST = 'TYPE_REQUEST'
export const TYPE_SUCCESS = 'TYPE_SUCCESS'
export const TYPE_FAILURE = 'TYPE_FAILURE'

export const ROLES_REQUEST = 'ROLES_REQUEST'
export const ROLES_SUCCESS = 'ROLES_SUCCESS'
export const ROLES_FAILURE = 'ROLES_FAILURE'

export const GROUPS_REQUEST = 'GROUPS_REQUEST'
export const GROUPS_SUCCESS = 'GROUPS_SUCCESS'
export const GROUPS_FAILURE = 'GROUPS_FAILURE'

export const DRAFT_DATA_REQUEST = 'DRAFT_DATA_REQUEST'
export const DRAFT_DATA_SUCCESS = 'DRAFT_DATA_SUCCESS'
export const DRAFT_DATA_FAILURE = 'DRAFT_DATA_FAILURE'

export const OUTBOX_DATA_REQUEST = 'OUTBOX_DATA_REQUEST'
export const OUTBOX_DATA_SUCCESS = 'OUTBOX_DATA_SUCCESS'
export const OUTBOX_DATA_FAILURE = 'OUTBOX_DATA_FAILURE'

export const INBOX_DATA_REQUEST = 'INBOX_DATA_REQUEST'
export const INBOX_DATA_SUCCESS = 'INBOX_DATA_SUCCESS'
export const INBOX_DATA_FAILURE = 'INBOX_DATA_FAILURE'

export const ENCLOSURE_DATA_REQUEST = 'ENCLOSURE_DATA_REQUEST'
export const ENCLOSURE_DATA_SUCCESS = 'ENCLOSURE_DATA_SUCCESS'
export const ENCLOSURE_DATA_FAILURE = 'ENCLOSURE_DATA_FAILURE'

export const NOTING_DATA_REQUEST = 'NOTING_DATA_REQUEST'
export const NOTING_DATA_SUCCESS = 'NOTING_DATA_SUCCESS'
export const NOTING_DATA_FAILURE = 'NOTING_DATA_FAILURE'

export const NOTING_FILE_REQUEST = 'NOTING_FILE_REQUEST'
export const NOTING_FILE_SUCCESS = 'NOTING_FILE_SUCCESS'
export const NOTING_FILE_FAILURE = 'NOTING_FILE_FAILURE'

export const ENCLOSURE_FILE_REQUEST = 'ENCLOSURE_FILE_REQUEST'
export const ENCLOSURE_FILE_SUCCESS = 'ENCLOSURE_FILE_SUCCESS'
export const ENCLOSURE_FILE_FAILURE = 'ENCLOSURE_FILE_FAILURE'

export const SEND_FILE_REQUEST = 'SEND_FILE_REQUEST'
export const SEND_FILE_SUCCESS = 'SEND_FILE_SUCCESS'
export const SEND_FILE_FAILURE = 'SEND_FILE_FAILURE'

export const FILE_REQUEST = 'FILE_REQUEST'
export const FILE_SUCCESS = 'FILE_SUCCESS'
export const FILE_FAILURE = 'FILE_FAILURE'

export const SFDT_REQUEST = 'SFDT_REQUEST'
export const SFDT_SUCCESS = 'SFDT_SUCCESS'
export const SFDT_FAILURE = 'SFDT_FAILURE'

export const CREATE_PF_REQUEST = 'CREATE_PF_REQUEST'
export const CREATE_PF_SUCCESS = 'CREATE_PF_SUCCESS'
export const CREATE_PF_FAILURE = 'CREATE_PF_FAILURE'

export const PA_REQUEST = 'PA_REQUEST'
export const PA_SUCCESS = 'PA_SUCCESS'
export const PA_FAILURE = 'PA_FAILURE'

export const PATYPE_REQUEST = 'PATYPE_REQUEST'
export const PATYPE_SUCCESS = 'PATYPE_SUCCESS'
export const PATYPE_FAILURE = 'PATYPE_FAILURE'

export const PF_REQUEST = 'PF_REQUEST'
export const PF_SUCCESS = 'PF_SUCCESS'
export const PF_FAILURE = 'PF_FAILURE'

export const PFILE_REQUEST = 'PFILE_REQUEST'
export const PFILE_SUCCESS = 'PFILE_SUCCESS'
export const PFILE_FAILURE = 'PFILE_FAILURE'

export const PA_TABLE_REQUEST = 'PA_TABLE_REQUEST'
export const PA_TABLE_SUCCESS = 'PA_TABLE_SUCCESS'
export const PA_TABLE_FAILURE = 'PA_TABLE_FAILURE'

export const ANNOT_REQUEST = 'ANNOT_REQUEST'
export const ANNOT_SUCCESS = 'ANNOT_SUCCESS'
export const ANNOT_FAILURE = 'ANNOT_FAILURE'

export const GET_ANNOT_REQUEST = 'GET_ANNOT_REQUEST'
export const GET_ANNOT_SUCCESS = 'GET_ANNOT_SUCCESS'
export const GET_ANNOT_FAILURE = 'GET_ANNOT_FAILURE'

export const SEND_FILES_REQUEST = 'SEND_FILES_REQUEST'
export const SEND_FILES_SUCCESS = 'SEND_FILES_SUCCESS'
export const SEND_FILES_FAILURE = 'SEND_FILES_FAILURE'

export const QICK_SIGN_REQUEST = 'QICK_SIGN_REQUEST'
export const QICK_SIGN_SUCCESS = 'QICK_SIGN_SUCCESS'
export const QICK_SIGN_FAILURE = 'QICK_SIGN_FAILURE'

export const SAVE_FILES_REQUEST = 'SAVE_FILES_REQUEST'
export const SAVE_FILES_SUCCESS = 'SAVE_FILES_SUCCESS'
export const SAVE_FILES_FAILURE = 'SAVE_FILES_FAILURE'

export const ANNEXURE_FILE_REQUEST = 'ANNEXURE_FILE_REQUEST'
export const ANNEXURE_FILE_SUCCESS = 'ANNEXURE_FILE_SUCCESS'
export const ANNEXURE_FILE_FAILURE = 'ANNEXURE_FILE_FAILURE'

export const ANNEXURE_LIST_REQUEST = 'ANNEXURE_LIST_REQUEST'
export const ANNEXURE_LIST_SUCCESS = 'ANNEXURE_LIST_SUCCESS'
export const ANNEXURE_LIST_FAILURE = 'ANNEXURE_LIST_FAILURE'

export const GROUP_LIST_REQUEST = 'GROUP_LIST_REQUEST'
export const GROUP_LIST_SUCCESS = 'GROUP_LIST_SUCCESS'
export const GROUP_LIST_FAILURE = 'GROUP_LIST_FAILURE'

export const HRM_LIST_REQUEST = 'HRM_LIST_REQUEST'
export const HRM_LIST_SUCCESS = 'HRM_LIST_SUCCESS'
export const HRM_LIST_FAILURE = 'HRM_LIST_FAILURE'

export const USER_ROLES_REQUEST = 'USER_ROLES_REQUEST'
export const USER_ROLES_SUCCESS = 'USER_ROLES_SUCCESS'
export const USER_ROLES_FAILURE = 'USER_ROLES_FAILURE'

export const MIS_LIST_REQUEST = 'MIS_LIST_REQUEST'
export const MIS_LIST_SUCCESS = 'MIS_LIST_SUCCESS'
export const MIS_LIST_FAILURE = 'MIS_LIST_FAILURE'

export const MIS_LIST_REQUEST1 = 'MIS_LIST_REQUEST1'
export const MIS_LIST_SUCCESS1 = 'MIS_LIST_SUCCESS1'
export const MIS_LIST_FAILURE1 = 'MIS_LIST_FAILURE1'

export const WAC_REQUEST = 'WAC_REQUEST'
export const WAC_SUCCESS = 'WAC_SUCCESS'
export const WAC_FAILURE = 'WAc_FAILURE'

export const INCOMING_WAC_REQUEST = 'INCOMING_WAC_REQUEST'
export const INCOMING_WAC_SUCCESS = 'INCOMING_WAC_SUCCESS'
export const INCOMING_WAC_FAILURE = 'INCOMING_WAc_FAILURE'

export const MIS_LIST_REQUEST2 = 'MIS_LIST_REQUEST2'
export const MIS_LIST_SUCCESS2 = 'MIS_LIST_SUCCESS2'
export const MIS_LIST_FAILURE2 = 'MIS_LIST_FAILURE2'

export const MIS_LIST_INCOMING_SECRET_WAC_REQUEST = 'MIS_LIST_INCOMING_SECRET_WAC_REQUEST'
export const MIS_LIST_INCOMING_SECRET_WAC_SUCCESS = 'MIS_LIST_INCOMING_SECRET_WAC_SUCCESS'
export const MIS_LIST_INCOMING_SECRET_WAC_FAILURE = 'MIS_LIST_INCOMING_SECRET_WAC_FAILURE'

export const MIS_LIST_REQUEST3 = 'MIS_LIST_REQUEST3'
export const MIS_LIST_SUCCESS3 = 'MIS_LIST_SUCCESS3'
export const MIS_LIST_FAILURE3 = 'MIS_LIST_FAILURE3'

export const MIS_LIST_SECRET_REQUEST = 'MIS_LIST_SECRET__REQUEST'
export const MIS_LIST_SECRET__SUCCESS = 'MIS_LIST_SECRET__SUCCESS'
export const MIS_LIST_SECRET__FAILURE = 'MIS_LIST_SECRET__FAILURE'

export const MIS_DETAIL_LIST_REQUEST = 'MIS_DETAIL_LIST_REQUEST'
export const MIS_DETAIL_LIST_SUCCESS = 'MIS_DETAIL_LIST_SUCCESS'
export const MIS_DETAIL_LIST_FAILURE = 'MIS_DETAIL_LIST_FAILURE'

export const MIS_DETAIL_LIST_INCOMING_WAC_REQUEST = 'MIS_DETAIL_LIST_INCOMING_WAC_REQUEST'
export const MIS_DETAIL_LIST_INCOMING_WAC_SUCCESS = 'MIS_DETAIL_LIST_INCOMING_WAC_SUCCESS'
export const MIS_DETAIL_LIST_INCOMING_WAC_FAILURE = 'MIS_DETAIL_LIST_INCOMING_WAC_FAILURE'

export const MIS_DETAIL_LIST_REQUEST3 = 'MIS_DETAIL_LIST_REQUEST3'
export const MIS_DETAIL_LIST_SUCCESS3 = 'MIS_DETAIL_LIST_SUCCESS3'
export const MIS_DETAIL_LIST_FAILURE3 = 'MIS_DETAIL_LIST_FAILURE3'

export const MIS_DETAIL_LIST_SECRET_WAC_REQUEST = 'MIS_DETAIL_LIST_SECRET_WAC_REQUEST'
export const MIS_DETAIL_LIST_SECRET_WAC_SUCCESS = 'MIS_DETAIL_LIST_SECRET_WAC_SUCCESS'
export const MIS_DETAIL_LIST_SECRET_WAC_FAILURE = 'MIS_DETAIL_LIST_SECRET_WAC_FAILURE'

export const MIS_DETAIL_LIST_REQUEST2 = 'MIS_DETAIL_LIST_REQUEST2'
export const MIS_DETAIL_LIST_SUCCESS2 = 'MIS_DETAIL_LIST_SUCCESS2'
export const MIS_DETAIL_LIST_FAILURE2 = 'MIS_DETAIL_LIST_FAILURE2'

export const MIS_DETAIL_LIST_INCOMING_SECRET_REQUEST = 'MIS_DETAIL_LIST_INCOMING_SECRET_REQUEST'
export const MIS_DETAIL_LIST_INCOMING_SECRET_SUCCESS = 'MIS_DETAIL_LIST_INCOMING_SECRET_SUCCESS'
export const MIS_DETAIL_LIST_INCOMING_SECRET_FAILURE = 'MIS_DETAIL_LIST_INCOMING_SECRET_FAILURE'

export const MIS_DETAIL_LIST_REQUEST1 = 'MIS_DETAIL_LIST_REQUEST1'
export const MIS_DETAIL_LIST_SUCCESS1 = 'MIS_DETAIL_LIST_SUCCESS1'
export const MIS_DETAIL_LIST_FAILURE1 = 'MIS_DETAIL_LIST_FAILURE1'

export const MIS_DETAIL_LIST_WAC_REQUEST = 'MIS_DETAIL_LIST_WAC_REQUEST'
export const MIS_DETAIL_LIST_WAC_SUCCESS = 'MIS_DETAIL_LIST_WAC_SUCCESS'
export const MIS_DETAIL_LIST_WAC_FAILURE = 'MIS_DETAIL_LIST_WAC_FAILURE'

export const DELETE_ANNEXURE_REQUEST = 'DELETE_ANNEXURE_REQUEST'
export const DELETE_ANNEXURE_SUCCESS = 'DELETE_ANNEXURE_SUCCESS'
export const DELETE_ANNEXURE_FAILURE = 'DELETE_ANNEXURE_FAILURE'

export const CREATE_PANOTING_REQUEST = 'CREATE_PANOTING_REQUEST'
export const CREATE_PANOTING_SUCCESS = 'CREATE_PANOTING_SUCCESS'
export const CREATE_PANOTING_FAILURE = 'CREATE_PANOTING_FAILURE'

export const FETCH_PANOTING_REQUEST = 'FETCH_PANOTING_REQUEST'
export const FETCH_PANOTING_SUCCESS = 'FETCH_PANOTING_SUCCESS'
export const FETCH_PANOTING_FAILURE = 'FETCH_PANOTING_FAILURE'

export const FETCH_PAENCLOSURE_REQUEST = 'FETCH_PAENCLOSURE_REQUEST'
export const FETCH_PAENCLOSURE_SUCCESS = 'FETCH_PAENCLOSURE_SUCCESS'
export const FETCH_PAENCLOSURE_FAILURE = 'FETCH_PAENCLOSURE_FAILURE'

export const FETCH_CARD_SECRET1_REQUEST = 'FETCH_CARD_SECRET1_REQUEST'
export const FETCH_CARD_SECRET1_SUCCESS = 'FETCH_CARD_SECRET1_SUCCESS'
export const FETCH_CARD_SECRET1_FAILURE = 'FETCH_CARD_SECRET1_FAILURE'

export const FETCH_CARD_SECRET2_REQUEST = 'FETCH_CARD_SECRET2_REQUEST'
export const FETCH_CARD_SECRET2_SUCCESS = 'FETCH_CARD_SECRET2_SUCCESS'
export const FETCH_CARD_SECRET2_FAILURE = 'FETCH_CARD_SECRET2_FAILURE'

export const FETCH_CARD_MIS2_REQUEST = 'FETCH_CARD_MIS2_REQUEST'
export const FETCH_CARD_MIS2_SUCCESS = 'FETCH_CARD_MIS2_SUCCESS'
export const FETCH_CARD_MIS2_FAILURE = 'FETCH_CARD_MIS2_FAILURE'

export const FETCH_CARD_MIS1_REQUEST = 'FETCH_CARD_MIS1_REQUEST'
export const FETCH_CARD_MIS1_SUCCESS = 'FETCH_CARD_MIS1_SUCCESS'
export const FETCH_CARD_MIS1_FAILURE = 'FETCH_CARD_MIS1_FAILURE'


export const CHART1_REQUEST = 'CHART1_REQUEST'
export const CHART1_SUCCESS = 'CHART1_SUCCESS'
export const CHART1_FAILURE = 'CHART1_FAILURE'

export const CHART2_REQUEST = 'CHART2_REQUEST'
export const CHART2_SUCCESS = 'CHART2_SUCCESS'
export const CHART2_FAILURE = 'CHART2_FAILURE'
